language: go

go:
  - 1.7

install:
    - go get github.com/mattn/goveralls
    - go get -d -v ./...

script:
    - go vet -x
    - go test -covermode=count -coverprofile=profile.cov -v github.com/unicok/unet/codec

after_success:
    - bash <(curl -s https://codecov.io/bash)